---
apiVersion: v1
kind: Service
metadata:
  name: beets
  namespace: default
  labels:
    app: beets
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8337
      protocol: TCP
  selector:
    app: beets
